### ISSUE TITLE
Library not work on NextJs

### ISSUE THREAD

**Issue by coolcorexix** [shunjizhan/react-folder-tree#10]
As I inspected, it is caused by:
-  Using style-loader in webpack config to include scss file, causing 'document is not defined' error 
![localhost_3000_read2](https://user-images.githubusercontent.com/25930830/110307414-73d4a280-8031-11eb-9276-e2cff2e45e15.png)

- The global object using self so it can not be used on Node.js, causing 'self is not defined' error

So to fix these in my opinion, we will have to change the webpack config and also usage of this library:
- Add `globalObject: 'this'` to `output` of webpack, as [here](https://webpack.js.org/configuration/output/#outputglobalobject)
- Remove style-loader and guide users to explicitly add scss file from their side, like how https://www.npmjs.com/package/react-dropdown are being used

**Comment by shunjizhan** [comment]
thanks for pointing this out! I am not super familiar with next.js, but in later versions will probably do some research on this. 

At the same time please try fork it to accommodate next.js : )

**Comment by phatNfqAsia** [comment]
hello @shunjizhan, I will try to draft a PR when I have time. Just promise me you dont ignore it hehe

**Comment by shunjizhan** [comment]
@phatNfqAsia sure! Your contribution is very welcomed, I will definitely not ignore it if it works

**Comment by admondtamang** [comment]
**Lazy loading** with **dynamic import** or **ssr false** worked for me.

```tsx
import dynamic from "next/dynamic";

const NavigationFolder = dynamic(() => import("./TreeFolder"), {
    loading: () => <p>Loading...</p>,
});
```


```tsx
const FolderTree = dynamic(() => import("react-folder-tree"), {
    ssr: false,
});

```

**Comment by phatNfqAsia** [comment]
@shunjizhan oh if it done the job we can close it now, but I also recommend you convert your library to dumb components so that user can adapt it better to their usecases, currently the logic (check/uncheck, actions) is in one package and it's hard for user to customize.

**Comment by coolcorexix** [comment]
@shunjizhan actually I solve a problem of mine based on your reply. Thanks a lot!

**Comment by shunjizhan** [comment]
> @shunjizhan actually I solve a problem of mine based on your reply. Thanks a lot!

do you mean @admondtamang 's reply haha? Thanks @admondtamang for the suggestion

**Comment by Djcarrillo6** [comment]
Hello!

Just wanted to confirm the solution mentioned above, as I was able to successfully debug the ReferenceError of 'self' not being defined within a Nextjs implementation of this module.  I dynamically imported the module as @admondtamang suggested and it debugged the issue! Posted my code below just for further context. Great library @shunjizhan!

PS.. I just created a testData.js file in my root, and imported it directly from there as opposed to importing the object from the module itself, however it is probably still possible through another solution/fix that uses dynamic importing.

```tsx
import React from 'react';
import dynamic from 'next/dynamic';
import { testData } from './testData';
const DynamicFileTreeImport = dynamic(() => import('react-folder-tree'), {
	ssr: false, // needed to prevent warning about dynamic component
});

const DocFileTree = () => {
	const onTreeStateChange = (state, event) => console.log(state, event);

	return <DynamicFileTreeImport data={testData} onChange={onTreeStateChange} />;
};

export default DocFileTree;
```

**Comment by shunjizhan** [comment]
Hi @Djcarrillo6 , 

Thanks for confirming this method works, this is definitely very helpful for people experiencing similar issue : )

I should probably add this example in the doc in the next version
