### ISSUE TITLE
...\react-folder-tree\dist\react-folder-tree.bundle.js:1:23299: Unexpected token (1:23299)

### ISSUE THREAD

**Issue by josanuz** [shunjizhan/react-folder-tree#14]
Getting an unexpected token error when the lib is installed using yarn/npm

**Comment by shunjizhan** [comment]
Hi, I just tried to install the lib in a fresh create-react-app, and it seems to work fine.

Could you please provide more details about how you use the lib when encounter this error? Which version are you using?

**Comment by shunjizhan** [comment]
check this out for basic usage
https://codesandbox.io/s/basic-tree-6crd3?file=/src/App.js

**Comment by shunjizhan** [comment]
closing this issue, let me know if it still doesn't work for you : )
