### ISSUE TITLE
support prop to control whether show checkbox or not

### ISSUE THREAD

**Issue by shenshanyoumu** [shunjizhan/react-folder-tree#15]
when I want a pure folder tree, I mean I don't need checkbox before each item

**Comment by shunjizhan** [comment]
sure! This is indeed what I planned to do next, will be out ASAP!

**Comment by shunjizhan** [comment]
@shenshanyoumu 
hey, just released a [new version](https://www.npmjs.com/package/react-folder-tree) that supports hiding checkbox! 

[this](https://github.com/shunjizhan/react-folder-tree#-hate-checkbox) is the doc for the new prop:
```tsx
<FolderTree
  data={ treeState }
  showCheckbox={ false }    // default: true
/>
```

Please check it out and let me know if there is anything breaking 😃

**Comment by shenshanyoumu** [comment]
@shunjizhan ,well done😃
