### ISSUE TITLE
Add and delete feature not showing on top of the tree

### ISSUE THREAD

**Issue by Raunak-Agrawal** [shunjizhan/react-folder-tree#2]

**Comment by dmadmin1** [comment]
Try it

 <FolderTree
        data={testData}
        showToolbar={true}
      />

**Comment by hoadv** [comment]
Try it
> `<FolderTree data={testData} showToolbar={true} />`

**Comment by hoadv** [comment]
> _No description provided._

Try it
> `<FolderTree data={testData} showToolbar={true} />`

**Comment by shunjizhan** [comment]
hi, just upgraded the folder tree to a brand new version, please check it out and try it out : )
https://www.npmjs.com/package/react-folder-tree
