### ISSUE TITLE
Expand docs for reserved keys and internal data structure

### ISSUE THREAD

**Issue by alaisgomes** [shunjizhan/react-folder-tree#21]
Hi!
I noticed that the docs mention the [reserved keys that you can use](https://github.com/shunjizhan/react-folder-tree#-custom-initial-state) to define the nodes. But I think it is missing information on what custom keys you **_cannot_** use.
I noticed this because I had a custom key called `path`, but it killed the file tree (rendering was all messy) and threw a bunch of `Uncaught TypeError: Cannot read property 'children' of undefined`.
Then I realized that both keys `path` and `_id` are used internally.
I'm suggesting you add that to the readme as well, could help avoid confusion.

Great work on the library though. Thanks!

**Comment by shunjizhan** [comment]
Hi!

Thanks for pointing this out! And indeed you are very right, `path` and `_id` are used internally, and should not be customized. 

I will add this to the doc in the next version update ; )

**Comment by shunjizhan** [comment]
Hi Aline @alaisgomes ,

Just released a [new version](https://www.npmjs.com/package/react-folder-tree), with updated [doc](https://github.com/shunjizhan/react-folder-tree#-custom-initial-state) telling people not to customize `path`. 

Again, really appreciate your suggestions, and please let me know if the new version doesn't work for you : )
