### ISSUE TITLE
Option to prevent allowing edits (read-only mode)

### ISSUE THREAD

**Issue by michaelaflores** [shunjizhan/react-folder-tree#24]
We can use `onNameClick` to prevent showing the edit UI when the name is clicked, but if they click the icon they'll see it anyways. We can then override the entire icon, but it would be nice to either simply have a prop that doesn't allow any editing, or also allow an `onIconClick` prop to override the onClick for icons without making an entire icon to do so.

**Comment by shunjizhan** [comment]
Hi Michael,

Yeah! I think a `ready only` mode would be pretty useful, will add a prop to do it.

Thanks for the suggestion!

**Comment by shunjizhan** [comment]
Hi Michael, @michaelaflores 

just released a [new version](https://www.npmjs.com/package/react-folder-tree), which supports `read only` mode!

basically we can now do something like ([doc](https://github.com/shunjizhan/react-folder-tree#-read-only))
```ts
<FolderTree
  data={ treeState }
  showCheckbox={ false }    // hiding checkbox is not required but recommended for better UX
  readOnly                  // <== here!!
/>
```

Again, really appreciate your suggestion, and please let me know if it doesn't work for you : )

**Comment by michaelaflores** [comment]
Thanks @shunjizhan 🙏🏼
