### ISSUE TITLE
Trigger caret click on name click

### ISSUE THREAD

**Issue by jamesmacwilliam** [shunjizhan/react-folder-tree#32]
for folders, it is common to allow for both the label click and the caret click to expand / contract the folder contents.  Is there a way to do this?

**Comment by shunjizhan** [comment]
Hi James,

Currently there is no direct way to do it, but yeah this would be a nice feature to have! 

To accommodate it, we can do a 1-line change in the source code to pass the expand / contract handler to `onNameClick`

change [this line](
https://github.com/shunjizhan/react-folder-tree/blob/master/src/components/TreeNode/TreeNode.jsx#L118
) from 
```ts
!isEditing && onNameClick({ defaultOnClick, nodeData });
```
to
```ts
// openMe and closeMe is the handler
!isEditing && onNameClick({ defaultOnClick, nodeData, openMe, closeMe });
```

to use it
```ts
const onNameClick = ({ nodeData, openMe, closeMe }) => {
  const { isOpen } = nodeData;
   if (isOpen) { 
    closeMe()
  } else {
    openMe()
  }
};

```
If you are interested, just fork this lib and `yarn build` yourself : ) 

In later version I might add all of the [state handlers](https://github.com/shunjizhan/react-folder-tree/blob/master/src/components/TreeNode/TreeNode.jsx#L42) as param to `onNameClick` to provide more versatile customization

**Comment by jamesmacwilliam** [comment]
This is exactly what I was looking for, thank you @shunjizhan !
