### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by SatyamKr07** [shunjizhan/react-folder-tree#33]
I am trying to use it in Next.js project and i am getting this error:

Server Error
ReferenceError: self is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
.next\server\pages\page2.js (1:0) @ Object.react-folder-tree

> 1 | module.exports = require("react-folder-tree");;
Call Stack
__webpack_require__
.next\server\webpack-runtime.js (21:0)

**Comment by shunjizhan** [comment]
Hi,

We had another discussion about Nextjs here #10, can you try if [using dynamic import](https://github.com/shunjizhan/react-folder-tree/issues/10#issuecomment-836183781) fixes it?

**Comment by shunjizhan** [comment]
quick update, dynamic import should fix this issue, example code can be found [here](https://github.com/shunjizhan/react-folder-tree/issues/10#issuecomment-904177865)
