### ISSUE TITLE
Per tree item events

### ISSUE THREAD

**Issue by NicolaeBasso** [shunjizhan/React-Folder-Tree#42]
Hey, thanks for cool component!

Is there a way to attach some new logic to single elements when mouse events occur?
For example, I would like to add a tooltip with different contents on top of  items when I hover each.

**Comment by shunjizhan** [comment]
Hi Nick,

Seems that we currently don't have a way to attach mouse event handler 😢

I guess it won't be too hard to add a `onNodeHover` callback in next version, which has similar arguments with the existing `onNameClick` [handler](https://github.com/shunjizhan/react-folder-tree#-custom-onclick-for-node-names). 

However, I am not sure so far what's the best way to support "DOM related" callback, I mean for "data related callback", it is super easy, like what we have: 

```ts
const onNameClick = ({  nodeData }) => { ... };
```

if we need to show a tooltip, maybe we can have something like this? Although it doesn't look very 'React'
```ts
const onNodeHover = ({  nodeData, refToNodeDOM }) => { showTooltip(refToNodeDOM); };
```

Let me know if you have any idea about it, and thanks for this feature suggestion!

By the way if we just need to support a very specific hover handler (like a tooltip), but not a general on hover interface, it should be achievable, feel free to fork the code and implement a react-folder-tree-with-tooltip, and I am happy to answer any question about the codes : )

**Comment by shunjizhan** [comment]
and for 'Per tree item', events could be distinguished by it's node data, for example

```ts
const onNodeHover = ({ nodeData, refToNodeDOM }) => { 
  if (nodeData.tooltipInfo) {
    showTooltip(refToNodeDOM, nodeData.tooltipInfo);
  }
 };
```
let me know if you have any better ideas.

**Comment by NicolaeBasso** [comment]
Well, I've just added blueprint tooltip wrapper to tree items and it worked for me...
Not the best option for a 'light weight lib' to add blueprint to dependencies though;

**Comment by shunjizhan** [comment]
glad to hear it worked out for you!
