### ISSUE TITLE
how to have all the nodes closed by default

### ISSUE THREAD

**Issue by zilahir** [shunjizhan/react-folder-tree#5]
at the moment by initialisation all the node are having `open` state. 

is there a way to render then in `closed` state?

**Comment by shunjizhan** [comment]
hi, just upgraded the folder tree to a brand new version, please check it out and try it out : )
https://www.npmjs.com/package/react-folder-tree

**Comment by shunjizhan** [comment]
now we can set `initOpenStatus` to `'close'`
