### ISSUE TITLE
custom css for selected file, folder

### ISSUE THREAD

**Issue by arunkumar413** [shunjizhan/React-Folder-Tree#62]
I'd like to highlight the file name being edited currently.

I tried the below css but it didn't work. Could you please guide me on how to add my own css styles.

```
.TreeNodde .TreeNodeToolBar {
  background-color: gray;
}

.TreeNodde .editingName {
  background-color: blue;
}

```

**Comment by purbe** [comment]
try this one 

.FolderTree .TreeNode .TreeNodeToolBar {
background-color: gray;
}

**Comment by shunjizhan** [comment]
duplicate of #49,
