### ISSUE TITLE
onNameClick nodeData not fetched

### ISSUE THREAD

**Issue by purbe** [shunjizhan/React-Folder-Tree#63]
in tsx file, when i'm calling the function
 const onNameClick = ({ defaultOnClick, nodeData }) => { console.log(nodeData)}

console is showing  " undefined ".
pls tell me, how to solve this.

**Comment by shunjizhan** [comment]
can you provide a repo/codesanbox link to reproduce it? Thanks

**Comment by purbe** [comment]
here is the codesandbox link , pls let me know why nodeData undefined
https://codesandbox.io/s/trusting-lovelace-qfp10o?file=/src/tree.tsx

thanks

**Comment by shunjizhan** [comment]
`console.log("nodedata = " + JSON.stringify(nodeData));` worked for me

![Screen Shot 2022-06-20 at 17 13 08](https://user-images.githubusercontent.com/16548786/174568644-f4268d0d-aaa9-47c8-b674-766c659d1d72.png)

**Comment by purbe** [comment]
got it. thanks a lot
