### ISSUE TITLE
Add Typescript support with .d.ts file

### ISSUE THREAD

**Issue by NicolaLovo** [shunjizhan/React-Folder-Tree#66]
It would be great to have typescript support for typescript programmers, so they don't have to declare their own .d.ts file for this awsome module.

**Comment by shunjizhan** [comment]
Hey, thanks for the suggestion, I am indeed planning to rewrite the whole lib to TS, just has been too busy to do it. Will let you know once it's done 😃

**Comment by NicolaLovo** [comment]
Thank you! I really appreciate your component, it saved me a lot of work.

**Comment by mard0n** [comment]
Love this component. And typescript would make it perfect

**Comment by skillseeker-io** [comment]
Me three please haha

**Comment by IanStorm** [comment]
Hey @shunjizhan,
I was thinking about providing a Pull Request including TypeScript typings, i.e. a `.d.ts` file. These might not be 100% accurate, but it could help people now, while they are waiting for your TS rewrite of the lib.
Is a PR welcome? Would you have time to review it?

**Comment by shunjizhan** [comment]
sure! welcome to provide a PR, I can review it

**Comment by shunjizhan** [comment]
just published a new version with types support, thanks to @IanStorm 's contribution! Feel free to try out the [latest version](https://www.npmjs.com/package/react-folder-tree) and let me know if there is any issue
